# Generated by Django 5.2.8 on 2025-11-16 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Основний телефон"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Додатковий телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Місто / Село"
                    ),
                ),
                (
                    "nova_poshta_branch",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Відділення або поштомат НП",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
