# Generated by Django 5.0 on 2025-11-07 09:30
# (Примітка: Я генерую це на основі ваших моделей)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва бренду')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('new', 'Нове замовлення'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('shipping_type', models.CharField(choices=[('pickup', 'Самовивіз'), ('nova_poshta', 'Нова Пошта')], default='pickup', max_length=20, verbose_name='Тип доставки')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ПІБ отримувача')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто/Село')),
                ('nova_poshta_branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Відділення НП')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва шини (модель)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('width', models.IntegerField(verbose_name='Ширина (напр. 205)')),
                ('profile', models.IntegerField(verbose_name='Профіль (напр. 55)')),
                ('diameter', models.IntegerField(verbose_name='Діаметр (напр. 16)')),
                ('seasonality', models.CharField(choices=[('winter', 'Зимові'), ('summer', 'Літні'), ('all-season', 'Всесезонні')], max_length=20, verbose_name='Сезонність')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна з прайсу (закупка)')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand', verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (на момент покупки)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Товар')),
            ],
        ),
    ]
