# Generated by Django 5.0 on 2025-11-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL Фото (Вставляти посилання сюди)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото (НЕ ВИКОРИСТОВУВАТИ)'),
        ),
    ]
