# Generated by Django 5.0 on 2025-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна з прайсу (закупка)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.IntegerField(default=0, verbose_name='Діаметр (напр. 16)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.IntegerField(default=0, verbose_name='Профіль (напр. 55)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seasonality',
            field=models.CharField(choices=[('winter', 'Зимові'), ('summer', 'Літні'), ('all-season', 'Всесезонні')], default='all-season', max_length=20, verbose_name='Сезонність'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина (напр. 205)'),
        ),
    ]
