# Generated by Django 5.2.8 on 2025-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="seasonality",
            field=models.CharField(
                choices=[
                    ("winter", "Зимові"),
                    ("summer", "Літні"),
                    ("all-season", "Всесезонні"),
                ],
                default="all-season",
                max_length=20,
            ),
        ),
    ]
