import os
import django
from django.core.management import call_command
from django.db import connection

# Налаштування
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'TireShop.settings')
django.setup()

print("🚀 Починаю ручне виправлення бази даних...")

# 1. "Фейкова" міграція
# Ми кажемо Django, що міграція 0007 вже виконана. 
# Це прибирає помилки "table already exists" для Банера і Країни.
try:
    print("--> Маркуємо міграцію 0007 як виконану...")
    call_command('migrate', 'store', '0007', fake=True)
    print("OK.")
except Exception as e:
    print(f"Увага (не критично): {e}")

# 2. Достворюємо те, що пропустили (Налаштування і Знижки)
# Оскільки ми зробили 'fake', Django не створив нові таблиці. Робимо це вручну SQL-кодом.
with connection.cursor() as cursor:
    print("--> Створення таблиці SiteSettings...")
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS store_sitesettings (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            global_markup numeric(5, 2) NOT NULL
        );
    ''')
    
    print("--> Додавання колонки знижки (discount_percent)...")
    try:
        cursor.execute('ALTER TABLE store_product ADD COLUMN IF NOT EXISTS discount_percent integer NOT NULL DEFAULT 0;')
    except Exception:
        # Якщо колонка вже є, ігноруємо помилку
        pass

print("✅ Успішно! База даних повністю синхронізована.")
