import os
import django
from django.db import connection

# Налаштування
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'TireShop.settings')
django.setup()

print("🚑 Відновлюю таблицю SiteBanner...")

with connection.cursor() as cursor:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS store_sitebanner (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            title varchar(100) NOT NULL,
            image varchar(100),
            image_url varchar(1024),
            link varchar(200),
            is_active boolean NOT NULL DEFAULT true,
            created_at timestamp with time zone NOT NULL DEFAULT NOW()
        );
    ''')

print("✅ Таблицю store_sitebanner успішно створено! Сайт має запрацювати.")
