import os
import django
from django.db import connection

# Налаштування
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'TireShop.settings')
django.setup()

print("🚑 Починаю комплексний ремонт бази даних...")

with connection.cursor() as cursor:
    # 1. Додаємо колонку Знижки (discount_percent)
    print("--> Додаю колонку discount_percent...")
    try:
        cursor.execute("ALTER TABLE store_product ADD COLUMN IF NOT EXISTS discount_percent integer NOT NULL DEFAULT 0;")
        print("   OK.")
    except Exception as e:
        print(f"   (Вже є або помилка): {e}")

    # 2. Відновлюємо таблицю Банерів (SiteBanner)
    print("--> Перевіряю таблицю SiteBanner...")
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS store_sitebanner (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            title varchar(100) NOT NULL,
            image varchar(100),
            image_url varchar(1024),
            link varchar(200),
            is_active boolean NOT NULL DEFAULT true,
            created_at timestamp with time zone NOT NULL DEFAULT NOW()
        );
    ''')

    # 3. Відновлюємо таблицю Налаштувань (SiteSettings)
    print("--> Перевіряю таблицю SiteSettings...")
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS store_sitesettings (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            global_markup numeric(5, 2) NOT NULL
        );
    ''')

print("✅ Ремонт завершено! Всі таблиці та колонки на місці.")
