import os
import django
from django.db import connection

# Налаштування
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'TireShop.settings')
django.setup()

print("🚑 Створюю таблицю для фото 'Про нас'...")

with connection.cursor() as cursor:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS store_aboutimage (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            image varchar(100) NOT NULL,
            image_url varchar(1024),
            description varchar(200) NOT NULL,
            created_at timestamp with time zone NOT NULL
        );
    ''')

print("✅ Таблицю store_aboutimage успішно створено!")
